theme: jekyll-theme-minimal
  skin: dark
title: "Heximer Investment Management, Inc"
google_analytics: UA-20951855-2
description: "We provide discretionary asset management, financial planning, and investment advice tailored to your investment goals and objectives. Our clients enjoy peace of mind and financial security backed by trust and confidence." 
logo: /assets/logo.png
