baseurl: '/'
permalink: pretty
title: 'Heximer Investment Management, Inc'
description: This is my site. 
services:
  - name: Resources
    permalink: /resources/<service_name>

logo:
  mobile: "images/logo/logo.png"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.png"
  #desktop_height: "45px"
  desktop_width: "120px"
  url: "/"

home: 
  limit_services: 6

collections:
  Resources:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "resources"
    values:
      layout: "resources"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
